### ISSUE TITLE
warnings in ga4gh topic branch

### ISSUE THREAD

**Issue by diekhans** [Jeltje/ga4gh-schemas#31] opened 2015-09-12 16:05 UTC
Lots of warnings that need fixed  To deal with git merge crap, this is now in jetlje/documentation2 or
ga4gh topic branch documentation.

```
/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/common.rst:59: WARNING: Field list ends without a blank line; unexpected unindent.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/metadata.rst:8: WARNING: duplicate Avro object description of Strand.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/metadata.rst:11: WARNING: Field list ends without a blank line; unexpected unindent.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/metadata.rst:16: WARNING: duplicate Avro object description of Position.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/metadata.rst:38: WARNING: duplicate Avro object description of ExternalIdentifier.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/metadata.rst:56: WARNING: duplicate Avro object description of CigarOperation.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/metadata.rst:59: WARNING: Field list ends without a blank line; unexpected unindent.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/metadata.rst:105: WARNING: duplicate Avro object description of CigarUnit.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/readmethods.rst:4: WARNING: duplicate Avro object description of Strand.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/readmethods.rst:7: WARNING: Field list ends without a blank line; unexpected unindent.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/readmethods.rst:12: WARNING: duplicate Avro object description of Position.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/readmethods.rst:34: WARNING: duplicate Avro object description of ExternalIdentifier.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/readmethods.rst:52: WARNING: duplicate Avro object description of CigarOperation.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/readmethods.rst:55: WARNING: Field list ends without a blank line; unexpected unindent.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/readmethods.rst:101: WARNING: duplicate Avro object description of CigarUnit.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/readmethods.rst:122: WARNING: duplicate Avro object description of GAException.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/readmethods.rst:127: WARNING: duplicate Avro object description of Experiment.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/readmethods.rst:208: WARNING: duplicate Avro object description of Dataset.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/readmethods.rst:358: WARNING: Inline literal start-string without end-string.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/readmethods.rst:387: WARNING: Inline literal start-string without end-string.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/readmethods.rst:391: WARNING: Inline literal start-string without end-string.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/readmethods.rst:414: WARNING: Inline literal start-string without end-string.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/reads.rst:84: WARNING: duplicate Avro object description of Strand.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/reads.rst:87: WARNING: Field list ends without a blank line; unexpected unindent.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/reads.rst:92: WARNING: duplicate Avro object description of Position.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/reads.rst:114: WARNING: duplicate Avro object description of ExternalIdentifier.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/reads.rst:132: WARNING: duplicate Avro object description of CigarOperation.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/reads.rst:135: WARNING: Field list ends without a blank line; unexpected unindent.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/reads.rst:181: WARNING: duplicate Avro object description of CigarUnit.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/reads.rst:202: WARNING: duplicate Avro object description of Experiment.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/reads.rst:283: WARNING: duplicate Avro object description of Dataset.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/reads.rst:318: WARNING: duplicate Avro object description of Program.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/reads.rst:351: WARNING: duplicate Avro object description of ReadStats.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/reads.rst:376: WARNING: duplicate Avro object description of ReadGroup.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/reads.rst:433: WARNING: Inline literal start-string without end-string.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/reads.rst:441: WARNING: duplicate Avro object description of ReadGroupSet.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/reads.rst:462: WARNING: Inline literal start-string without end-string.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/reads.rst:466: WARNING: Inline literal start-string without end-string.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/reads.rst:476: WARNING: duplicate Avro object description of LinearAlignment.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/reads.rst:489: WARNING: Inline literal start-string without end-string.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/reads.rst:498: WARNING: duplicate Avro object description of Fragment.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/reads.rst:512: WARNING: duplicate Avro object description of ReadAlignment.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/referencemethods.rst:4: WARNING: duplicate Avro object description of Strand.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/referencemethods.rst:7: WARNING: Field list ends without a blank line; unexpected unindent.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/referencemethods.rst:12: WARNING: duplicate Avro object description of Position.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/referencemethods.rst:34: WARNING: duplicate Avro object description of ExternalIdentifier.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/referencemethods.rst:52: WARNING: duplicate Avro object description of CigarOperation.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/referencemethods.rst:55: WARNING: Field list ends without a blank line; unexpected unindent.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/referencemethods.rst:101: WARNING: duplicate Avro object description of CigarUnit.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/referencemethods.rst:122: WARNING: duplicate Avro object description of GAException.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/referencemethods.rst:182: WARNING: Inline literal start-string without end-string.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/referencemethods.rst:194: WARNING: Inline literal start-string without end-string.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/references.rst:7: WARNING: duplicate Avro object description of Strand.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/references.rst:10: WARNING: Field list ends without a blank line; unexpected unindent.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/references.rst:15: WARNING: duplicate Avro object description of Position.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/references.rst:37: WARNING: duplicate Avro object description of ExternalIdentifier.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/references.rst:55: WARNING: duplicate Avro object description of CigarOperation.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/references.rst:58: WARNING: Field list ends without a blank line; unexpected unindent.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/references.rst:104: WARNING: duplicate Avro object description of CigarUnit.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/references.rst:125: WARNING: duplicate Avro object description of Reference.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/references.rst:180: WARNING: Inline literal start-string without end-string.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/references.rst:183: WARNING: duplicate Avro object description of ReferenceSet.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/references.rst:192: WARNING: Inline literal start-string without end-string.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/variantmethods.rst:4: WARNING: duplicate Avro object description of GAException.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/variantmethods.rst:9: WARNING: duplicate Avro object description of Strand.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/variantmethods.rst:12: WARNING: Field list ends without a blank line; unexpected unindent.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/variantmethods.rst:17: WARNING: duplicate Avro object description of Position.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/variantmethods.rst:39: WARNING: duplicate Avro object description of ExternalIdentifier.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/variantmethods.rst:57: WARNING: duplicate Avro object description of CigarOperation.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/variantmethods.rst:60: WARNING: Field list ends without a blank line; unexpected unindent.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/variantmethods.rst:106: WARNING: duplicate Avro object description of CigarUnit.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/variantmethods.rst:215: WARNING: Inline literal start-string without end-string.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/variants.rst:9: WARNING: duplicate Avro object description of Strand.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/variants.rst:12: WARNING: Field list ends without a blank line; unexpected unindent.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/variants.rst:17: WARNING: duplicate Avro object description of Position.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/variants.rst:39: WARNING: duplicate Avro object description of ExternalIdentifier.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/variants.rst:57: WARNING: duplicate Avro object description of CigarOperation.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/variants.rst:60: WARNING: Field list ends without a blank line; unexpected unindent.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/variants.rst:106: WARNING: duplicate Avro object description of CigarUnit.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/variants.rst:127: WARNING: duplicate Avro object description of VariantSetMetadata.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/variants.rst:168: WARNING: duplicate Avro object description of VariantSet.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/variants.rst:198: WARNING: duplicate Avro object description of CallSet.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/variants.rst:215: WARNING: Inline literal start-string without end-string.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/variants.rst:232: WARNING: duplicate Avro object description of Call.

/home/travis/build/ga4gh/schemas/target/generated-docs/rst/schemas/variants.rst:292: WARNING: duplicate Avro object description of Variant.

ok

testSchemaProperties (test_protocol.TestValidateSchemas) ... ok

```

---

**Comment by Jeltje** [comment] 2015-09-12 18:47
These all come from the schemas, I don't know what the problem is. They show up fine in the web pages.

**Comment by diekhans** [comment] 2015-09-12 19:55
Herb? Hellllpppppp

**Comment by Jeltje** [comment] 2015-09-15 02:25
These duplicated messages arise because there are a lot of duplicated records in the 
/target/generated-docs/rst/schemas/*rst files
For instance:
.. avro:enum:: Strand
occurs in all but methods.rst.
This must happen somewhere between the .avdl and the .rst files, because the records are not duplicated in the schemas themselves.

...Herb?

**Comment by hjellinek** [comment] 2015-09-18 19:28
We've been using Waflle to view issues across repos, and somehow this issue doesn't show up in my Waffle list. :-(
Sorry I missed it!  I'm looking into it now.

**Comment by hjellinek** [comment] 2015-09-18 19:52
Note to self:
The problem seems to be that Sphinx (I think it is) is obeying

``` avro
    import idl "common.avdl";
```

and the other 12 `import idl` statements by textually inserting the contents of the imported file.

The avro-tools `idl` command appears responsible for this.

**Comment by diekhans** [comment] 2015-09-18 20:26
Ouch... there has to be someway to keep if redoing this ;-)

**Comment by hjellinek** [comment] 2015-09-18 20:31
Is the problem (a) the many (57, to be exact) annoying messages, or (b) that the output HTML is bad?

For what it's worth, the HTML seems OK to me and my browser.  The prose links to the generated schema docs just fine.

I have eliminated the `duplicate Avro object description` warnings - let me know if that's all you're after and I'll push it.

**Comment by hjellinek** [comment] 2015-09-18 21:27
No, I bet you want the duplicate definitions removed from the generated documentation.

That may be tough.  The Avro parser seems to handle 'import idl', as I mentioned above, by textually inserting the `import`ed file into the file containing the `import idl` statement where it occurs.  The parser is a fundamental component of the Avro toolset, and changing it is not a task to be taken lightly.

**Comment by diekhans** [comment] 2015-09-18 23:59
We need to fix it, otherwise warnings are all ignored and then
when they mean something, it doesn't help.

HTML validator complains about some things, but mostly obsolete
attributes.

**Comment by hjellinek** [comment] 2015-09-21 16:10
OK, fix what?: the pointless warnings (done, not checked in yet) or the Avro parser (potentially massive project)?

**Comment by hjellinek** [comment] 2015-09-21 21:31
Closing this.  I checked the work in to schemas/documentation.

**Closed as completed by hjellinek** 2015-09-21 21:31 UTC
